<?php
/**
 * Store Configuration — Design Tokens
 * Auto-generated by Kiwi UI Generator V2
 * DO NOT edit manually — regenerate from demo
 */

return [
    'colors' => [
        'primary' => '#2c3e50',
        'secondary' => '#e74c3c',
        'accent' => '#3498db',
    ],

    'typography' => [
        'sans' => [
            'fontFamily' => 'Inter',
        ],
    ],

    'spacing' => [
        'section' => '80px',
    ],

    'borderRadius' => [
        'card' => '12px',
    ],

];