/**
 * Tailwind CSS Configuration
 * Auto-generated by Kiwi UI Generator V2
 * DO NOT edit manually — regenerate from demo
 */

module.exports = {
  content: [
    './templates/**/*.php',
    './custom-templates/**/*.php',
    './src/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'primary': 'var(--wz-primary)',
        'secondary': 'var(--wz-secondary)',
        'accent': 'var(--wz-accent)',
      },
      fontSize: {
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
      },
      spacing: {
        'section': '80px',
      },
      borderRadius: {
        'card': '12px',
      },
      screens: {
        'md': '768px',
        'lg': '1024px',
      },
    },
  },
  plugins: [],
};