"""G0 Foundation Generator — Generate 16 core WordPress theme files."""

from pathlib import Path
from typing import Dict, Any, List


class G0FoundationGenerator:
    """
    Generate G0 Foundation files for WordPress theme.

    16 files:
    - functions.php (theme bootstrap)
    - style.css (theme header)
    - Plugin.php (theme engine class)
    - index.php (fallback template)
    - header.php (site header)
    - footer.php (site footer)
    - single.php (single post)
    - archive.php (archive)
    - search.php (search results)
    - 404.php (not found)
    - sidebar.php (sidebar)
    - comments.php (comments)
    - package.json (npm config)
    - webpack.config.js (build config)
    - .gitignore
    - README.md
    """

    def __init__(self, tokens: Dict[str, Any], theme_name: str):
        self.tokens = tokens
        self.theme_name = theme_name
        self.theme_slug = theme_name.lower().replace(' ', '-')

    def generate_all(self, theme_dir: Path) -> List[str]:
        """Generate all G0 Foundation files."""
        created_files = []

        # Core PHP files
        created_files.append(self._generate_functions_php(theme_dir))
        created_files.append(self._generate_style_css(theme_dir))
        created_files.append(self._generate_plugin_php(theme_dir))

        # Template files
        created_files.append(self._generate_index_php(theme_dir))
        created_files.append(self._generate_header_php(theme_dir))
        created_files.append(self._generate_footer_php(theme_dir))
        created_files.append(self._generate_single_php(theme_dir))
        created_files.append(self._generate_archive_php(theme_dir))
        created_files.append(self._generate_search_php(theme_dir))
        created_files.append(self._generate_404_php(theme_dir))
        created_files.append(self._generate_sidebar_php(theme_dir))
        created_files.append(self._generate_comments_php(theme_dir))

        # Build config files
        created_files.append(self._generate_package_json(theme_dir))
        created_files.append(self._generate_webpack_config(theme_dir))
        created_files.append(self._generate_gitignore(theme_dir))
        created_files.append(self._generate_readme(theme_dir))

        return created_files

    def _generate_functions_php(self, theme_dir: Path) -> str:
        """Generate functions.php — theme bootstrap."""
        content = f"""<?php
/**
 * Theme Functions — {self.theme_name}
 * Auto-generated by Kiwi UI Generator V2
 */

if (!defined('ABSPATH')) {{
    exit;
}}

// Load theme engine
require_once __DIR__ . '/Plugin.php';

// Initialize theme
add_action('after_setup_theme', function() {{
    // Theme support
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', ['search-form', 'comment-form', 'comment-list', 'gallery', 'caption']);

    // Register menus
    register_nav_menus([
        'primary' => __('Primary Menu', '{self.theme_slug}'),
        'footer' => __('Footer Menu', '{self.theme_slug}'),
    ]);
}});

// Enqueue styles and scripts
add_action('wp_enqueue_scripts', function() {{
    wp_enqueue_style('{self.theme_slug}-style', get_stylesheet_uri(), [], '1.0.0');
    wp_enqueue_style('{self.theme_slug}-main', get_template_directory_uri() . '/dist/main.css', [], '1.0.0');
    wp_enqueue_script('{self.theme_slug}-main', get_template_directory_uri() . '/dist/main.js', [], '1.0.0', true);
}});
"""
        file_path = theme_dir / 'functions.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_style_css(self, theme_dir: Path) -> str:
        """Generate style.css — theme header."""
        content = f"""/*
Theme Name: {self.theme_name}
Theme URI: https://wezone.vn
Author: Wezone Team
Author URI: https://wezone.vn
Description: Auto-generated WordPress theme by Kiwi UI Generator V2
Version: 1.0.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: {self.theme_slug}
*/

/* Theme styles are compiled from src/main.css via Tailwind */
"""
        file_path = theme_dir / 'style.css'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_plugin_php(self, theme_dir: Path) -> str:
        """Generate Plugin.php — theme engine class."""
        content = f"""<?php
/**
 * Theme Engine — {self.theme_name}
 * Auto-generated by Kiwi UI Generator V2
 */

namespace Wezone\\Theme\\{self.theme_name.replace('-', '').replace(' ', '')};

if (!defined('ABSPATH')) {{
    exit;
}}

class Plugin {{
    private static $instance = null;

    public static function instance() {{
        if (self::$instance === null) {{
            self::$instance = new self();
        }}
        return self::$instance;
    }}

    private function __construct() {{
        $this->init_hooks();
    }}

    private function init_hooks() {{
        add_action('init', [$this, 'register_post_types']);
        add_action('widgets_init', [$this, 'register_sidebars']);
    }}

    public function register_post_types() {{
        // Register custom post types here
    }}

    public function register_sidebars() {{
        register_sidebar([
            'name' => __('Primary Sidebar', '{self.theme_slug}'),
            'id' => 'sidebar-1',
            'before_widget' => '<div id="%1$s" class="widget %2$s">',
            'after_widget' => '</div>',
            'before_title' => '<h3 class="widget-title">',
            'after_title' => '</h3>',
        ]);
    }}
}}

// Initialize
Plugin::instance();
"""
        file_path = theme_dir / 'Plugin.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_index_php(self, theme_dir: Path) -> str:
        """Generate index.php — fallback template."""
        content = """<?php get_header(); ?>

<main class="container mx-auto px-4 py-8">
    <?php if (have_posts()) : ?>
        <?php while (have_posts()) : the_post(); ?>
            <article id="post-<?php the_ID(); ?>" <?php post_class('mb-8'); ?>>
                <h2 class="text-3xl font-bold mb-4">
                    <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                </h2>
                <div class="prose max-w-none">
                    <?php the_excerpt(); ?>
                </div>
            </article>
        <?php endwhile; ?>
    <?php else : ?>
        <p><?php _e('No posts found.'); ?></p>
    <?php endif; ?>
</main>

<?php get_footer(); ?>
"""
        file_path = theme_dir / 'index.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_header_php(self, theme_dir: Path) -> str:
        """Generate header.php — site header."""
        primary_color = self.tokens.get('colors', {}).get('primary', '#000000')
        content = f"""<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

<header class="site-header bg-white shadow-md" style="border-bottom: 2px solid {primary_color};">
    <div class="container mx-auto px-4 py-4 flex justify-between items-center">
        <div class="site-branding">
            <a href="<?php echo esc_url(home_url('/')); ?>" class="text-2xl font-bold">
                <?php bloginfo('name'); ?>
            </a>
        </div>
        <nav class="main-navigation">
            <?php
            wp_nav_menu([
                'theme_location' => 'primary',
                'menu_class' => 'flex gap-6',
                'container' => false,
            ]);
            ?>
        </nav>
    </div>
</header>
"""
        file_path = theme_dir / 'header.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_footer_php(self, theme_dir: Path) -> str:
        """Generate footer.php — site footer."""
        content = """
<footer class="site-footer bg-gray-900 text-white py-12 mt-16">
    <div class="container mx-auto px-4">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
                <h3 class="text-xl font-bold mb-4"><?php bloginfo('name'); ?></h3>
                <p><?php bloginfo('description'); ?></p>
            </div>
            <div>
                <h3 class="text-xl font-bold mb-4"><?php _e('Quick Links'); ?></h3>
                <?php
                wp_nav_menu([
                    'theme_location' => 'footer',
                    'menu_class' => 'space-y-2',
                    'container' => false,
                ]);
                ?>
            </div>
            <div>
                <h3 class="text-xl font-bold mb-4"><?php _e('Contact'); ?></h3>
                <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?></p>
            </div>
        </div>
    </div>
</footer>

<?php wp_footer(); ?>
</body>
</html>
"""
        file_path = theme_dir / 'footer.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_single_php(self, theme_dir: Path) -> str:
        """Generate single.php — single post template."""
        content = """<?php get_header(); ?>

<main class="container mx-auto px-4 py-8">
    <?php while (have_posts()) : the_post(); ?>
        <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
            <h1 class="text-4xl font-bold mb-4"><?php the_title(); ?></h1>
            <div class="prose max-w-none">
                <?php the_content(); ?>
            </div>
        </article>
    <?php endwhile; ?>
</main>

<?php get_footer(); ?>
"""
        file_path = theme_dir / 'single.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_archive_php(self, theme_dir: Path) -> str:
        """Generate archive.php — archive template."""
        content = """<?php get_header(); ?>

<main class="container mx-auto px-4 py-8">
    <h1 class="text-4xl font-bold mb-8"><?php the_archive_title(); ?></h1>

    <?php if (have_posts()) : ?>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <?php while (have_posts()) : the_post(); ?>
                <article <?php post_class('bg-white rounded-lg shadow p-6'); ?>>
                    <h2 class="text-2xl font-bold mb-2">
                        <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                    </h2>
                    <?php the_excerpt(); ?>
                </article>
            <?php endwhile; ?>
        </div>
    <?php endif; ?>
</main>

<?php get_footer(); ?>
"""
        file_path = theme_dir / 'archive.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_search_php(self, theme_dir: Path) -> str:
        """Generate search.php — search results template."""
        content = """<?php get_header(); ?>

<main class="container mx-auto px-4 py-8">
    <h1 class="text-4xl font-bold mb-8">
        <?php printf(__('Search Results for: %s'), get_search_query()); ?>
    </h1>

    <?php if (have_posts()) : ?>
        <?php while (have_posts()) : the_post(); ?>
            <article <?php post_class('mb-8'); ?>>
                <h2 class="text-2xl font-bold mb-2">
                    <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                </h2>
                <?php the_excerpt(); ?>
            </article>
        <?php endwhile; ?>
    <?php else : ?>
        <p><?php _e('No results found.'); ?></p>
    <?php endif; ?>
</main>

<?php get_footer(); ?>
"""
        file_path = theme_dir / 'search.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_404_php(self, theme_dir: Path) -> str:
        """Generate 404.php — not found template."""
        content = """<?php get_header(); ?>

<main class="container mx-auto px-4 py-16 text-center">
    <h1 class="text-6xl font-bold mb-4">404</h1>
    <p class="text-2xl mb-8"><?php _e('Page Not Found'); ?></p>
    <a href="<?php echo esc_url(home_url('/')); ?>" class="btn bg-primary text-white px-8 py-3 rounded-lg">
        <?php _e('Go Home'); ?>
    </a>
</main>

<?php get_footer(); ?>
"""
        file_path = theme_dir / '404.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_sidebar_php(self, theme_dir: Path) -> str:
        """Generate sidebar.php — sidebar template."""
        content = """<?php if (is_active_sidebar('sidebar-1')) : ?>
    <aside class="sidebar">
        <?php dynamic_sidebar('sidebar-1'); ?>
    </aside>
<?php endif; ?>
"""
        file_path = theme_dir / 'sidebar.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_comments_php(self, theme_dir: Path) -> str:
        """Generate comments.php — comments template."""
        content = """<?php if (post_password_required()) return; ?>

<div id="comments" class="comments-area mt-8">
    <?php if (have_comments()) : ?>
        <h2 class="text-2xl font-bold mb-4">
            <?php printf(_n('One Comment', '%1$s Comments', get_comments_number()), number_format_i18n(get_comments_number())); ?>
        </h2>

        <ol class="comment-list space-y-4">
            <?php wp_list_comments(['style' => 'ol', 'short_ping' => true]); ?>
        </ol>
    <?php endif; ?>

    <?php comment_form(); ?>
</div>
"""
        file_path = theme_dir / 'comments.php'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_package_json(self, theme_dir: Path) -> str:
        """Generate package.json — npm config."""
        import json
        content = {
            "name": self.theme_slug,
            "version": "1.0.0",
            "description": f"{self.theme_name} WordPress Theme",
            "scripts": {
                "dev": "webpack --mode development --watch",
                "build": "webpack --mode production"
            },
            "devDependencies": {
                "webpack": "^5.88.0",
                "webpack-cli": "^5.1.4",
                "css-loader": "^6.8.1",
                "style-loader": "^3.3.3",
                "postcss": "^8.4.27",
                "postcss-loader": "^7.3.3",
                "tailwindcss": "^3.3.3",
                "autoprefixer": "^10.4.14"
            }
        }
        file_path = theme_dir / 'package.json'
        file_path.write_text(json.dumps(content, indent=2), encoding='utf-8')
        return str(file_path)

    def _generate_webpack_config(self, theme_dir: Path) -> str:
        """Generate webpack.config.js — build config."""
        content = """const path = require('path');

module.exports = {
    entry: './src/main.css',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'main.js',
    },
    module: {
        rules: [
            {
                test: /\\.css$/,
                use: [
                    'style-loader',
                    'css-loader',
                    'postcss-loader',
                ],
            },
        ],
    },
};
"""
        file_path = theme_dir / 'webpack.config.js'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_gitignore(self, theme_dir: Path) -> str:
        """Generate .gitignore."""
        content = """node_modules/
dist/
*.log
.DS_Store
"""
        file_path = theme_dir / '.gitignore'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)

    def _generate_readme(self, theme_dir: Path) -> str:
        """Generate README.md."""
        content = f"""# {self.theme_name}

Auto-generated WordPress theme by Kiwi UI Generator V2.

## Installation

1. Upload theme to `/wp-content/themes/{self.theme_slug}/`
2. Run `npm install` to install dependencies
3. Run `npm run build` to compile assets
4. Activate theme in WordPress admin

## Development

```bash
npm run dev  # Watch mode
npm run build  # Production build
```

## Features

- Tailwind CSS integration
- Responsive design
- Custom post types support
- Widget-ready sidebars
- SEO-friendly markup

## License

GPL v2 or later
"""
        file_path = theme_dir / 'README.md'
        file_path.write_text(content, encoding='utf-8')
        return str(file_path)
