"""Store Config Generator — Convert design tokens to store-config.php + tailwind.config.js"""

import json
from pathlib import Path
from typing import Dict, Any


class StoreConfigGenerator:
    """
    Generate store-config.php and tailwind.config.js from design tokens.

    Usage:
        generator = StoreConfigGenerator(tokens)
        php_code = generator.generate_store_config()
        js_code = generator.generate_tailwind_config()
    """

    def __init__(self, tokens: Dict[str, Any]):
        self.tokens = tokens

    def generate_store_config(self) -> str:
        """
        Generate store-config.php from tokens.

        Returns:
            PHP code string
        """
        lines = [
            "<?php",
            "/**",
            " * Store Configuration — Design Tokens",
            " * Auto-generated by Kiwi UI Generator V2",
            " * DO NOT edit manually — regenerate from demo",
            " */",
            "",
            "return [",
        ]

        # Colors
        if "colors" in self.tokens:
            lines.append("    'colors' => [")
            for name, value in self.tokens["colors"].items():
                lines.append(f"        '{name}' => '{value}',")
            lines.append("    ],")
            lines.append("")

        # Typography
        if "typography" in self.tokens:
            lines.append("    'typography' => [")
            for key, value in self.tokens["typography"].items():
                if isinstance(value, dict):
                    # Nested structure (e.g., fontSize: {base: '16px', lg: '18px'})
                    lines.append(f"        '{key}' => [")
                    for sub_key, sub_value in value.items():
                        if isinstance(sub_value, str):
                            lines.append(f"            '{sub_key}' => '{sub_value}',")
                        else:
                            lines.append(f"            '{sub_key}' => {json.dumps(sub_value)},")
                    lines.append("        ],")
                elif isinstance(value, str):
                    # Flat structure (e.g., fontFamily: 'Inter, sans-serif')
                    lines.append(f"        '{key}' => '{value}',")
                else:
                    lines.append(f"        '{key}' => {json.dumps(value)},")
            lines.append("    ],")
            lines.append("")

        # Spacing
        if "spacing" in self.tokens:
            lines.append("    'spacing' => [")
            for name, value in self.tokens["spacing"].items():
                lines.append(f"        '{name}' => '{value}',")
            lines.append("    ],")
            lines.append("")

        # Border Radius
        if "borderRadius" in self.tokens:
            lines.append("    'borderRadius' => [")
            for name, value in self.tokens["borderRadius"].items():
                lines.append(f"        '{name}' => '{value}',")
            lines.append("    ],")
            lines.append("")

        lines.append("];")

        return "\n".join(lines)

    def generate_tailwind_config(self) -> str:
        """
        Generate tailwind.config.js from tokens.

        Returns:
            JavaScript code string
        """
        lines = [
            "/**",
            " * Tailwind CSS Configuration",
            " * Auto-generated by Kiwi UI Generator V2",
            " * DO NOT edit manually — regenerate from demo",
            " */",
            "",
            "module.exports = {",
            "  content: [",
            "    './templates/**/*.php',",
            "    './custom-templates/**/*.php',",
            "    './src/**/*.js',",
            "  ],",
            "  theme: {",
            "    extend: {",
        ]

        # Colors (map to CSS variables)
        if "colors" in self.tokens:
            lines.append("      colors: {")
            for name in self.tokens["colors"].keys():
                css_var = name.replace("_", "-")
                lines.append(f"        '{name}': 'var(--wz-{css_var})',")
            lines.append("      },")

        # Typography (fontSize)
        if "typography" in self.tokens:
            lines.append("      fontSize: {")
            for scale_name, scale_config in self.tokens["typography"].items():
                if "fontSize" in scale_config:
                    font_size = scale_config["fontSize"]
                    line_height = scale_config.get("lineHeight", "1.5")
                    letter_spacing = scale_config.get("letterSpacing", "0")
                    font_weight = scale_config.get("fontWeight", "400")

                    lines.append(f"        '{scale_name}': ['{font_size}', {{")
                    lines.append(f"          lineHeight: '{line_height}',")
                    lines.append(f"          letterSpacing: '{letter_spacing}',")
                    lines.append(f"          fontWeight: '{font_weight}',")
                    lines.append("        }],")
            lines.append("      },")

            # Font Family
            lines.append("      fontFamily: {")
            for scale_name, scale_config in self.tokens["typography"].items():
                if "fontFamily" in scale_config:
                    font_family = scale_config["fontFamily"]
                    lines.append(f"        '{scale_name}': ['{font_family}', 'sans-serif'],")
            lines.append("      },")

        # Spacing
        if "spacing" in self.tokens:
            lines.append("      spacing: {")
            for name, value in self.tokens["spacing"].items():
                lines.append(f"        '{name}': '{value}',")
            lines.append("      },")

        # Border Radius
        if "borderRadius" in self.tokens:
            lines.append("      borderRadius: {")
            for name, value in self.tokens["borderRadius"].items():
                lines.append(f"        '{name}': '{value}',")
            lines.append("      },")

        # Screens (mobile-first breakpoints)
        lines.append("      screens: {")
        lines.append("        'md': '768px',")
        lines.append("        'lg': '1024px',")
        lines.append("      },")

        lines.append("    },")
        lines.append("  },")
        lines.append("  plugins: [],")
        lines.append("};")

        return "\n".join(lines)

    def generate_css_variables(self) -> str:
        """
        Generate CSS variables for colors (to be included in src/main.css).

        Returns:
            CSS code string
        """
        lines = [
            "/**",
            " * CSS Variables — Design Tokens",
            " * Auto-generated by Kiwi UI Generator V2",
            " */",
            "",
            ":root {",
        ]

        if "colors" in self.tokens:
            for name, value in self.tokens["colors"].items():
                css_var = name.replace("_", "-")
                lines.append(f"  --wz-{css_var}: {value};")

        lines.append("}")

        return "\n".join(lines)

    def save_to_theme(self, theme_path: str) -> Dict[str, str]:
        """
        Save generated files to theme folder.

        Args:
            theme_path: Path to theme folder (e.g., themes/sfvn-institutional)

        Returns:
            Dict with file paths and status
        """
        theme_dir = Path(theme_path)
        theme_dir.mkdir(parents=True, exist_ok=True)

        results = {}

        # store-config.php
        store_config_path = theme_dir / "store-config.php"
        store_config_path.write_text(self.generate_store_config(), encoding="utf-8")
        results["store-config.php"] = str(store_config_path)

        # tailwind.config.js
        tailwind_config_path = theme_dir / "tailwind.config.js"
        tailwind_config_path.write_text(self.generate_tailwind_config(), encoding="utf-8")
        results["tailwind.config.js"] = str(tailwind_config_path)

        # src/main.css (CSS variables)
        src_dir = theme_dir / "src"
        src_dir.mkdir(exist_ok=True)
        main_css_path = src_dir / "main.css"

        css_content = [
            self.generate_css_variables(),
            "",
            "@tailwind base;",
            "@tailwind components;",
            "@tailwind utilities;",
        ]

        main_css_path.write_text("\n".join(css_content), encoding="utf-8")
        results["src/main.css"] = str(main_css_path)

        return results


def main():
    """CLI for testing store config generation."""
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))

    from generator.parsers.token_extractor import DesignTokenExtractor

    if len(sys.argv) < 3:
        print("Usage: python store_config_generator.py <demo_path> <theme_path>")
        sys.exit(1)

    demo_path = sys.argv[1]
    theme_path = sys.argv[2]

    # Extract tokens
    extractor = DesignTokenExtractor()
    tokens = extractor.extract_from_demo(demo_path)

    # Generate files
    generator = StoreConfigGenerator(tokens)
    results = generator.save_to_theme(theme_path)

    print("Generated files:")
    for filename, filepath in results.items():
        print(f"  [OK] {filename} -> {filepath}")


if __name__ == "__main__":
    main()