<?php
/**
 * Kiwi UI Test Theme Functions
 *
 * Entry point for theme functionality.
 * Generated by Kiwi Generator Phase 1
 *
 * @package kiwi-ui-test
 * @generated 2026-05-25T10:56:27.092862
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Theme constants
define( 'KIWI_UI_TEST_VERSION', '1.0.0' );
define( 'KIWI_UI_TEST_DIR', get_template_directory() );
define( 'KIWI_UI_TEST_URI', get_template_directory_uri() );

// Load core modules
require_once KIWI_UI_TEST_DIR . '/inc/helpers.php';
require_once KIWI_UI_TEST_DIR . '/inc/security.php';
require_once KIWI_UI_TEST_DIR . '/inc/setup.php';
require_once KIWI_UI_TEST_DIR . '/inc/seo.php';

// Load design system
if ( file_exists( KIWI_UI_TEST_DIR . '/inc/design-system.php' ) ) {
	require_once KIWI_UI_TEST_DIR . '/inc/design-system.php';
}

// Enqueue styles and scripts
add_action( 'wp_enqueue_scripts', 'kiwi_ui_test_enqueue_assets' );
function kiwi_ui_test_enqueue_assets() {
	// Tailwind CSS (compiled)
	wp_enqueue_style(
		'kiwi-ui-test-tailwind',
		KIWI_UI_TEST_URI . '/assets/css/tailwind.css',
		[],
		KIWI_UI_TEST_VERSION
	);

	// Main JS
	wp_enqueue_script(
		'kiwi-ui-test-main',
		KIWI_UI_TEST_URI . '/assets/js/main.js',
		[],
		KIWI_UI_TEST_VERSION,
		true
	);

	// Localize script with theme config
	wp_localize_script(
		'kiwi-ui-test-main',
		'wzTheme',
		[
			'ajaxUrl' => admin_url( 'admin-ajax.php' ),
			'nonce'   => wp_create_nonce( 'kiwi-ui-test_nonce' ),
			'config'  => function_exists( 'wz_config' ) ? wz_config() : [],
		]
	);
}
