<?php
/**
 * Store Configuration
 *
 * Single source of truth for Kiwi UI Test brand identity and settings.
 * Accessed via wz_config('key', $default) helper.
 *
 * Generated by Kiwi Generator Phase 1
 * @generated 2026-05-25T10:56:26.919976
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return [
	'name'    => 'Kiwi UI Test',
	'tagline' => '',
	'phone'   => '',
	'email'   => '',
	'address' => '',
	'logo'    => '',

	'theme' => [
		'primary'   => '#3b82f6',
		'secondary' => '#8b5cf6',
		'accent'    => '#3b82f6',
		'font'      => 'Inter, sans-serif',
		'radius'    => 'md',
	],

	'social' => [
		'zalo_url'     => '',
		'facebook_url' => '',
		'youtube_url'  => '',
		'tiktok_url'   => '',
	],

	'analytics' => [
		'ga4_id'         => '',
		'fb_pixel_id'    => '',
		'google_ads_id'  => '',
	],

	'shipping' => [
		'free_ship_threshold' => 0,
		'fees' => [],
	],

	'seo' => [
		'site_url'    => home_url(),
		'og_image'    => '',
		'description' => '',
	],

	'footer' => [
		'copyright'  => '© ' . date('Y') . ' Kiwi UI Test. All rights reserved.',
		'powered_by' => 'Powered by WeZone Commer',
	],
];
