/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		'./*.php',
		'./template-parts/**/*.php',
		'./wezone-templates/**/*.php',
		'./inc/**/*.php',
		'./assets/js/**/*.js',
	],
	theme: {
		extend: {
			colors: {
				primary: 'var(--wz-primary)',
				secondary: 'var(--wz-secondary)',
				accent: 'var(--wz-accent)',
				surface: 'var(--wz-surface)',
				'surface-dim': 'var(--wz-surface-dim)',
				'surface-container': 'var(--wz-surface-container)',
				background: 'var(--wz-background)',
				'on-surface': 'var(--wz-on-surface)',
				'on-surface-variant': 'var(--wz-on-surface-variant)',
				error: 'var(--wz-error)',
				success: 'var(--wz-success)',
				warning: 'var(--wz-warning)',
				muted: 'var(--wz-muted)',
				outline: 'var(--wz-outline)',
			},
			spacing: {
				xs: 'var(--wz-spacing-xs)',
				sm: 'var(--wz-spacing-sm)',
				md: 'var(--wz-spacing-md)',
				lg: 'var(--wz-spacing-lg)',
				xl: 'var(--wz-spacing-xl)',
				'2xl': 'var(--wz-spacing-2xl)',
				gutter: 'var(--wz-gutter)',
			},
			borderRadius: {
				sm: 'var(--wz-radius-sm)',
				DEFAULT: 'var(--wz-radius)',
				md: 'var(--wz-radius-md)',
				lg: 'var(--wz-radius-lg)',
				xl: 'var(--wz-radius-xl)',
				card: 'var(--wz-radius-card)',
				full: 'var(--wz-radius-full)',
			},
			boxShadow: {
				sm: 'var(--wz-shadow-sm)',
				DEFAULT: 'var(--wz-shadow-md)',
				md: 'var(--wz-shadow-md)',
				lg: 'var(--wz-shadow-lg)',
				nav: 'var(--wz-shadow-nav)',
			},
			fontFamily: {
				sans: ['var(--wz-font-family)', 'system-ui', 'sans-serif'],
			},
			fontSize: {
				xs: 'var(--wz-text-xs)',
				sm: 'var(--wz-text-sm)',
				base: 'var(--wz-text-base)',
				lg: 'var(--wz-text-lg)',
				xl: 'var(--wz-text-xl)',
				'2xl': 'var(--wz-text-2xl)',
				'3xl': 'var(--wz-text-3xl)',
			},
			screens: {
				sm: '640px',
				md: '768px',
				lg: '1024px',
				xl: '1280px',
				'2xl': '1440px',
			},
			zIndex: {
				dropdown: 1000,
				sticky: 1020,
				fixed: 1030,
				'modal-backdrop': 1040,
				modal: 1050,
				tooltip: 1060,
			},
		},
	},
	plugins: [],
};
