<?php
/**
 * Kiwi Shop Demo Theme Functions
 *
 * Entry point for theme functionality.
 * Generated by Kiwi Generator Phase 1
 *
 * @package kiwi-with-mock-data
 * @generated 2026-05-25T11:09:37.746818
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Theme constants
define( 'KIWI_WITH_MOCK_DATA_VERSION', '1.0.0' );
define( 'KIWI_WITH_MOCK_DATA_DIR', get_template_directory() );
define( 'KIWI_WITH_MOCK_DATA_URI', get_template_directory_uri() );

// Load core modules
require_once KIWI_WITH_MOCK_DATA_DIR . '/inc/helpers.php';
require_once KIWI_WITH_MOCK_DATA_DIR . '/inc/security.php';
require_once KIWI_WITH_MOCK_DATA_DIR . '/inc/setup.php';
require_once KIWI_WITH_MOCK_DATA_DIR . '/inc/seo.php';

// Load design system
if ( file_exists( KIWI_WITH_MOCK_DATA_DIR . '/inc/design-system.php' ) ) {
	require_once KIWI_WITH_MOCK_DATA_DIR . '/inc/design-system.php';
}

// Enqueue styles and scripts
add_action( 'wp_enqueue_scripts', 'kiwi_with_mock_data_enqueue_assets' );
function kiwi_with_mock_data_enqueue_assets() {
	// Tailwind CSS (compiled)
	wp_enqueue_style(
		'kiwi-with-mock-data-tailwind',
		KIWI_WITH_MOCK_DATA_URI . '/assets/css/tailwind.css',
		[],
		KIWI_WITH_MOCK_DATA_VERSION
	);

	// Main JS
	wp_enqueue_script(
		'kiwi-with-mock-data-main',
		KIWI_WITH_MOCK_DATA_URI . '/assets/js/main.js',
		[],
		KIWI_WITH_MOCK_DATA_VERSION,
		true
	);

	// Localize script with theme config
	wp_localize_script(
		'kiwi-with-mock-data-main',
		'wzTheme',
		[
			'ajaxUrl' => admin_url( 'admin-ajax.php' ),
			'nonce'   => wp_create_nonce( 'kiwi-with-mock-data_nonce' ),
			'config'  => function_exists( 'wz_config' ) ? wz_config() : [],
		]
	);
}
