"""GitHub Issues integration."""

from dataclasses import dataclass
from typing import Dict, List, Optional
import subprocess
import json


@dataclass
class Issue:
    """GitHub issue."""
    number: int
    title: str
    body: str
    labels: List[str]
    state: str
    url: str


class GitHubIssuesAdapter:
    """Integrate Kiwi with GitHub Issues."""

    def __init__(self, repo: str):
        """
        Initialize GitHub Issues adapter.

        Args:
            repo: Repository (owner/name)
        """
        self.repo = repo

    def create_issue_from_violation(
        self,
        violation: Dict,
        lesson: Dict,
        file_path: str
    ) -> Optional[Issue]:
        """
        Create GitHub issue from Kiwi violation.

        Args:
            violation: Violation dict
            lesson: Lesson dict
            file_path: File path

        Returns:
            Created issue or None if failed
        """
        title = f"[Kiwi] {violation['severity']}: {violation['title']}"

        body = self._format_issue_body(violation, lesson, file_path)

        labels = self._get_labels(violation)

        try:
            result = subprocess.run(
                [
                    "gh", "issue", "create",
                    "--repo", self.repo,
                    "--title", title,
                    "--body", body,
                    "--label", ",".join(labels)
                ],
                capture_output=True,
                text=True,
                check=True,
                timeout=30,
            )

            # Parse issue URL from output
            issue_url = result.stdout.strip()
            issue_number = int(issue_url.split('/')[-1])

            return Issue(
                number=issue_number,
                title=title,
                body=body,
                labels=labels,
                state="open",
                url=issue_url
            )

        except subprocess.CalledProcessError:
            return None

    def _format_issue_body(
        self,
        violation: Dict,
        lesson: Dict,
        file_path: str
    ) -> str:
        """Format issue body from violation."""
        severity_icon = {
            'CRITICAL': '🔴',
            'HIGH': '🟡',
            'SUGGEST': '🔵'
        }.get(violation['severity'], '⚪')

        body = f"""## {severity_icon} {violation['severity']} Violation

**Lesson:** {violation['lesson_id']} - {violation['title']}

**File:** `{file_path}:{violation['line']}`

**Category:** {lesson.get('category', 'unknown')}

### Why This Matters

{lesson.get('why', 'No description available')}

### Bad Code

```
{violation.get('match_text', 'N/A')}
```

### Good Code

```
{lesson.get('good', 'See lesson for details')}
```

### How to Fix

{lesson.get('fix_suggestion', 'Apply the good code pattern above')}

---

*Auto-generated by [Kiwi Agent](https://github.com/wezone/kiwi)*
*Lesson ID: {violation['lesson_id']}*
"""

        return body

    def _get_labels(self, violation: Dict) -> List[str]:
        """Get labels for issue based on violation."""
        labels = ["kiwi", "code-quality"]

        # Add severity label
        severity = violation['severity'].lower()
        labels.append(f"severity:{severity}")

        # Add category label if available
        if 'category' in violation:
            labels.append(f"category:{violation['category']}")

        return labels

    def bulk_create_issues(
        self,
        violations: List[Dict],
        lessons: Dict[str, Dict],
        max_issues: int = 10
    ) -> List[Issue]:
        """
        Create multiple issues from violations.

        Args:
            violations: List of violations
            lessons: Dict of lesson_id -> lesson
            max_issues: Maximum issues to create

        Returns:
            List of created issues
        """
        created = []

        # Sort by severity
        sorted_violations = sorted(
            violations,
            key=lambda v: {'CRITICAL': 0, 'HIGH': 1, 'SUGGEST': 2}.get(v['severity'], 3)
        )

        for violation in sorted_violations[:max_issues]:
            lesson = lessons.get(violation['lesson_id'], {})
            issue = self.create_issue_from_violation(
                violation,
                lesson,
                violation['file']
            )

            if issue:
                created.append(issue)

        return created

    def close_issue(self, issue_number: int, comment: Optional[str] = None) -> bool:
        """
        Close an issue.

        Args:
            issue_number: Issue number
            comment: Optional closing comment

        Returns:
            True if successful
        """
        try:
            if comment:
                subprocess.run(
                    [
                        "gh", "issue", "comment", str(issue_number),
                        "--repo", self.repo,
                        "--body", comment
                    ],
                    check=True,
                    timeout=30,
                )

            subprocess.run(
                [
                    "gh", "issue", "close", str(issue_number),
                    "--repo", self.repo
                ],
                check=True,
                timeout=30,
            )

            return True

        except subprocess.CalledProcessError:
            return False