<?php
/**
 * Theme Functions — test-theme
 * Auto-generated by Kiwi UI Generator V2
 */

if (!defined('ABSPATH')) {
    exit;
}

// Load theme engine
require_once __DIR__ . '/Plugin.php';

// Initialize theme
add_action('after_setup_theme', function() {
    // Theme support
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', ['search-form', 'comment-form', 'comment-list', 'gallery', 'caption']);

    // Register menus
    register_nav_menus([
        'primary' => __('Primary Menu', 'test-theme'),
        'footer' => __('Footer Menu', 'test-theme'),
    ]);
});

// Enqueue styles and scripts
add_action('wp_enqueue_scripts', function() {
    wp_enqueue_style('test-theme-style', get_stylesheet_uri(), [], '1.0.0');
    wp_enqueue_style('test-theme-main', get_template_directory_uri() . '/dist/main.css', [], '1.0.0');
    wp_enqueue_script('test-theme-main', get_template_directory_uri() . '/dist/main.js', [], '1.0.0', true);
});
