<?php
/**
 * Theme Engine — test-theme
 * Auto-generated by Kiwi UI Generator V2
 */

namespace Wezone\Theme\testtheme;

if (!defined('ABSPATH')) {
    exit;
}

class Plugin {
    private static $instance = null;

    public static function instance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        $this->init_hooks();
    }

    private function init_hooks() {
        add_action('init', [$this, 'register_post_types']);
        add_action('widgets_init', [$this, 'register_sidebars']);
    }

    public function register_post_types() {
        // Register custom post types here
    }

    public function register_sidebars() {
        register_sidebar([
            'name' => __('Primary Sidebar', 'test-theme'),
            'id' => 'sidebar-1',
            'before_widget' => '<div id="%1$s" class="widget %2$s">',
            'after_widget' => '</div>',
            'before_title' => '<h3 class="widget-title">',
            'after_title' => '</h3>',
        ]);
    }
}

// Initialize
Plugin::instance();
