/**
 * Tailwind CSS Configuration
 * Auto-generated by Kiwi UI Generator V2
 * DO NOT edit manually — regenerate from demo
 */

module.exports = {
  content: [
    './templates/**/*.php',
    './custom-templates/**/*.php',
    './src/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'accent': 'var(--wz-accent)',
      },
      fontSize: {
      },
      fontFamily: {
      },
      spacing: {
        'section': '80px',
      },
      borderRadius: {
      },
      screens: {
        'md': '768px',
        'lg': '1024px',
      },
    },
  },
  plugins: [],
};