<?php
/**
 * Store Configuration — Design Tokens
 * Auto-generated by Kiwi UI Generator V2
 * DO NOT edit manually — regenerate from demo
 */

return [
    'colors' => [
        'accent' => '#f59e0b',
    ],

    'typography' => [
        'fontSize' => [
            'base' => '16px',
            'lg' => '18px',
        ],
    ],

    'spacing' => [
        'section' => '80px',
    ],

    'borderRadius' => [
    ],

];