<?php
/**
 * Kiwi Generator Test Theme Functions
 *
 * Entry point for theme functionality.
 * Generated by Kiwi Generator Phase 1
 *
 * @package kiwi-generator
 * @generated 2026-05-25T09:51:41.779898
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Theme constants
define( 'KIWI-GENERATOR_VERSION', '1.0.0' );
define( 'KIWI-GENERATOR_DIR', get_template_directory() );
define( 'KIWI-GENERATOR_URI', get_template_directory_uri() );

// Load core modules
require_once KIWI-GENERATOR_DIR . '/inc/helpers.php';
require_once KIWI-GENERATOR_DIR . '/inc/security.php';
require_once KIWI-GENERATOR_DIR . '/inc/setup.php';
require_once KIWI-GENERATOR_DIR . '/inc/seo.php';

// Load design system
if ( file_exists( KIWI-GENERATOR_DIR . '/inc/design-system.php' ) ) {
	require_once KIWI-GENERATOR_DIR . '/inc/design-system.php';
}

// Enqueue styles and scripts
add_action( 'wp_enqueue_scripts', 'kiwi_generator_enqueue_assets' );
function kiwi_generator_enqueue_assets() {
	// Tailwind CSS (compiled)
	wp_enqueue_style(
		'kiwi-generator-tailwind',
		KIWI-GENERATOR_URI . '/assets/css/tailwind.css',
		[],
		KIWI-GENERATOR_VERSION
	);

	// Main JS
	wp_enqueue_script(
		'kiwi-generator-main',
		KIWI-GENERATOR_URI . '/assets/js/main.js',
		[],
		KIWI-GENERATOR_VERSION,
		true
	);

	// Localize script with theme config
	wp_localize_script(
		'kiwi-generator-main',
		'wzTheme',
		[
			'ajaxUrl' => admin_url( 'admin-ajax.php' ),
			'nonce'   => wp_create_nonce( 'kiwi-generator_nonce' ),
			'config'  => function_exists( 'wz_config' ) ? wz_config() : [],
		]
	);
}
