<?php
/**
 * Store Configuration
 *
 * Single source of truth for Kiwi Generator Test brand identity and settings.
 * Accessed via wz_config('key', $default) helper.
 *
 * Generated by Kiwi Generator Phase 1
 * @generated 2026-05-25T09:51:41.662449
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return [
	'name'    => 'Kiwi Generator Test',
	'tagline' => 'Generated by Kiwi',
	'phone'   => '0123456789',
	'email'   => 'test@kiwi.local',
	'address' => '123 Test St',
	'logo'    => '',

	'theme' => [
		'primary'   => '#3b82f6',
		'secondary' => '#8b5cf6',
		'accent'    => '#3b82f6',
		'font'      => 'Inter, system-ui, sans-serif',
		'radius'    => 'md',
	],

	'social' => [
		'zalo_url'     => '',
		'facebook_url' => '',
		'youtube_url'  => '',
		'tiktok_url'   => '',
	],

	'analytics' => [
		'ga4_id'         => '',
		'fb_pixel_id'    => '',
		'google_ads_id'  => '',
	],

	'shipping' => [
		'free_ship_threshold' => 500000,
		'fees' => [],
	],

	'seo' => [
		'site_url'    => home_url(),
		'og_image'    => '',
		'description' => 'Generated by Kiwi',
	],

	'footer' => [
		'copyright'  => '© ' . date('Y') . ' Kiwi Generator Test. All rights reserved.',
		'powered_by' => 'Powered by WeZone Commer',
	],
];
