<?php
/**
 * Kiwi Phase3 Complete Theme Functions
 *
 * Entry point for theme functionality.
 * Generated by Kiwi Generator Phase 1
 *
 * @package kiwi-phase3-complete
 * @generated 2026-05-25T11:04:20.450322
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Theme constants
define( 'KIWI_PHASE3_COMPLETE_VERSION', '1.0.0' );
define( 'KIWI_PHASE3_COMPLETE_DIR', get_template_directory() );
define( 'KIWI_PHASE3_COMPLETE_URI', get_template_directory_uri() );

// Load core modules
require_once KIWI_PHASE3_COMPLETE_DIR . '/inc/helpers.php';
require_once KIWI_PHASE3_COMPLETE_DIR . '/inc/security.php';
require_once KIWI_PHASE3_COMPLETE_DIR . '/inc/setup.php';
require_once KIWI_PHASE3_COMPLETE_DIR . '/inc/seo.php';

// Load design system
if ( file_exists( KIWI_PHASE3_COMPLETE_DIR . '/inc/design-system.php' ) ) {
	require_once KIWI_PHASE3_COMPLETE_DIR . '/inc/design-system.php';
}

// Enqueue styles and scripts
add_action( 'wp_enqueue_scripts', 'kiwi_phase3_complete_enqueue_assets' );
function kiwi_phase3_complete_enqueue_assets() {
	// Tailwind CSS (compiled)
	wp_enqueue_style(
		'kiwi-phase3-complete-tailwind',
		KIWI_PHASE3_COMPLETE_URI . '/assets/css/tailwind.css',
		[],
		KIWI_PHASE3_COMPLETE_VERSION
	);

	// Main JS
	wp_enqueue_script(
		'kiwi-phase3-complete-main',
		KIWI_PHASE3_COMPLETE_URI . '/assets/js/main.js',
		[],
		KIWI_PHASE3_COMPLETE_VERSION,
		true
	);

	// Localize script with theme config
	wp_localize_script(
		'kiwi-phase3-complete-main',
		'wzTheme',
		[
			'ajaxUrl' => admin_url( 'admin-ajax.php' ),
			'nonce'   => wp_create_nonce( 'kiwi-phase3-complete_nonce' ),
			'config'  => function_exists( 'wz_config' ) ? wz_config() : [],
		]
	);
}
