"""R6 — Code Drafter: generate code at different completeness levels. 0 LLM token."""

import json
import re
from pathlib import Path

from .session_logger import _get_conn
from .output import KiwiOutput


def generate_skeleton(brief: KiwiOutput, theme_path: str) -> str:
    task_type = brief.content.get('target', 'generic')
    style = brief.content.get('style_pattern', '')

    conn = _get_conn()
    row = conn.execute(
        "SELECT structure FROM cross_theme_patterns "
        "WHERE task_type = ? ORDER BY success_count DESC LIMIT 1",
        (task_type,),
    ).fetchone()

    if not row:
        return _generic_skeleton(task_type, style)

    structure = json.loads(row[0]) if row[0] else {}
    sections = structure.get('sections', ['main'])
    layout = structure.get('layout_type', 'single-col')
    components = structure.get('components_used', [])

    skeleton = f"""<?php
/**
 * Template: {task_type}
 * Layout: {layout}
 * Generated by Kiwi R6 (skeleton)
 */

if ( ! function_exists( 'wezone_is_active' ) ) return;
?>

<section class="{style or 'py-8 md:py-12'}">
  <div class="max-w-7xl mx-auto px-4">
"""

    if layout == '2-col':
        skeleton += """    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div>
        <!-- TODO: main content -->
      </div>
      <div>
        <!-- TODO: sidebar/summary -->
      </div>
    </div>
"""
    elif layout == '3-col':
        skeleton += """    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <!-- TODO: 3 columns -->
    </div>
"""
    else:
        for section in sections[:5]:
            skeleton += f"""    <div>
      <!-- TODO: {section} -->
    </div>

"""

    if components:
        skeleton += "\n    <!-- Components:\n"
        for comp in components:
            skeleton += f"         wz_component('{comp}', [...]);\n"
        skeleton += "    -->\n"

    skeleton += """  </div>
</section>
"""
    return skeleton


def generate_draft(brief: KiwiOutput, theme_path: str) -> dict:
    task_type = brief.content.get('target', 'generic')
    theme_name = Path(theme_path).name

    reference = _find_best_reference(task_type, theme_name)
    if not reference:
        skeleton = generate_skeleton(brief, theme_path)
        return {'code': skeleton, 'changes': ['no_reference_found']}

    ref_path = Path(reference['file'])
    if not ref_path.exists():
        skeleton = generate_skeleton(brief, theme_path)
        return {'code': skeleton, 'changes': ['reference_file_missing']}

    ref_code = ref_path.read_text(encoding='utf-8', errors='ignore')

    target_style = _query_style_knowledge(theme_name)
    ref_style = _query_style_knowledge(reference['theme'])

    draft_code = _swap_style_tokens(ref_code, ref_style, target_style)

    changes = []
    for key in target_style:
        if key in ref_style and ref_style[key] != target_style[key]:
            changes.append(f"{key}: {ref_style[key]} -> {target_style[key]}")

    return {'code': draft_code, 'reference': str(ref_path), 'changes': changes}


def generate_final(brief: KiwiOutput, theme_path: str) -> dict:
    draft = generate_draft(brief, theme_path)
    task_type = brief.content.get('target', 'generic')
    draft['target_path'] = _determine_target_path(task_type, theme_path)
    return draft


def check_code_quality(code: str) -> bool:
    """Returns False if CRITICAL issues found in generated code."""
    critical_patterns = [
        r'wc_get_product',
        r'WC\(\)',
        r'\$product->',
        r'__\w+--\w+',
    ]
    for pattern in critical_patterns:
        if re.search(pattern, code):
            return False

    if 'wezone_is_active' not in code and '<?php' in code:
        return False

    return True


def _find_best_reference(task_type: str, target_theme: str) -> dict | None:
    conn = _get_conn()
    row = conn.execute(
        "SELECT themes_applied FROM cross_theme_patterns "
        "WHERE task_type = ? AND success_count >= 3 "
        "ORDER BY success_count DESC LIMIT 1",
        (task_type,),
    ).fetchone()

    if not row:
        return None

    themes = json.loads(row[0]) if row[0] else []
    target_style = _query_style_knowledge(target_theme)

    best_match = None
    best_score = -1.0

    for theme in themes:
        if theme == target_theme:
            continue
        theme_style = _query_style_knowledge(theme)
        score = _compute_style_similarity(target_style, theme_style)
        if score > best_score:
            best_score = score
            best_match = theme

    if not best_match:
        return None

    file_path = _find_task_file(task_type, best_match)
    if not file_path:
        return None

    return {'theme': best_match, 'file': file_path, 'similarity': best_score}


def _query_style_knowledge(theme: str) -> dict:
    conn = _get_conn()
    rows = conn.execute(
        "SELECT pattern_key, value FROM style_knowledge "
        "WHERE theme = ? AND times_seen >= 2",
        (theme,),
    ).fetchall()
    return {r[0]: r[1] for r in rows}


def _compute_style_similarity(style_a: dict, style_b: dict) -> float:
    if not style_a or not style_b:
        return 0.0
    keys = set(list(style_a.keys()) + list(style_b.keys()))
    if not keys:
        return 0.0
    matches = sum(1 for k in keys if style_a.get(k) == style_b.get(k))
    return matches / len(keys)


def _swap_style_tokens(code: str, source_style: dict, target_style: dict) -> str:
    result = code
    for key in target_style:
        if key not in source_style or source_style[key] == target_style[key]:
            continue
        old_val = source_style[key]
        new_val = target_style[key]

        if key == 'radius':
            result = result.replace(f"rounded-{old_val}", f"rounded-{new_val}")
        elif key == 'spacing_base':
            result = re.sub(rf'py-{old_val}(\s)', f'py-{new_val}\\1', result)
        elif key == 'spacing_md':
            result = re.sub(rf'md:py-{old_val}(\s|")', f'md:py-{new_val}\\1', result)
        elif key == 'container':
            result = result.replace(f"max-w-{old_val}", f"max-w-{new_val}")
        elif key == 'shadow':
            result = result.replace(f"shadow-{old_val}", f"shadow-{new_val}")
    return result


def _determine_target_path(task_type: str, theme_path: str) -> str:
    path_map = {
        'checkout_page': 'templates/checkout.php',
        'cart_page': 'templates/cart.php',
        'product_page': 'templates/single-product.php',
        'home_page': 'templates/home.php',
        'archive_page': 'templates/archive.php',
        'account_page': 'templates/account/dashboard.php',
        'login_page': 'templates/account/login.php',
        'search_page': 'templates/search.php',
        'thankyou_page': 'templates/thank-you.php',
    }
    relative = path_map.get(task_type, f'templates/{task_type}.php')
    return str(Path(theme_path) / relative)


def _generic_skeleton(task_type: str, style: str) -> str:
    return f"""<?php
/**
 * Template: {task_type}
 * Generated by Kiwi R6 (generic skeleton)
 */

if ( ! function_exists( 'wezone_is_active' ) ) return;
?>

<section class="{style or 'py-8 md:py-12'}">
  <div class="max-w-7xl mx-auto px-4">
    <!-- TODO: implement {task_type} -->
  </div>
</section>
"""


def _find_task_file(task_type: str, theme: str) -> str | None:
    from .context_assembler import PROJECT_ROOT

    theme_dir = PROJECT_ROOT / "themes" / theme
    if not theme_dir.exists():
        return None

    path_map = {
        'checkout_page': 'templates/checkout.php',
        'cart_page': 'templates/cart.php',
        'product_page': 'templates/single-product.php',
        'home_page': 'templates/home.php',
        'archive_page': 'templates/archive.php',
        'account_page': 'templates/account/dashboard.php',
        'login_page': 'templates/account/login.php',
        'search_page': 'templates/search.php',
        'thankyou_page': 'templates/thank-you.php',
        'hero_component': 'template-parts/home/hero.php',
        'header_component': 'template-parts/header.php',
        'footer_component': 'template-parts/footer.php',
    }

    relative = path_map.get(task_type)
    if not relative:
        return None

    candidate = theme_dir / relative
    if candidate.exists():
        return str(candidate)
    return None